### ISSUE TITLE
Add Atom/RSS feed for news items and events

### ISSUE THREAD

**Issue by bencomp** [nl-rse/nl-rse.github.io#69]
As a user of feed reader software and member of the NL-RSE community, I would like to have posts and events pop up in my feed reader through an Atom or RSS feed. It would be awesome if events were published in an iCalendar-feed as well.

The webpages suggest that there is a feed at `/feed.xml`, but there is no resource there.

**Comment by benvanwerkhoven** [comment]
Hi Ben,

The reason that it is suggested that there is such a file is probably because jekyll or the minima template that we use assume such a file is there. I have no idea how to produce such a file if it isn't done automatically. If you know how to do this or how we can enable jekyll to do this, then please feel free to contribute this to the website!

**Comment by c-martinez** [comment]
Hi Bens

Thanks for the suggestion. Just a though -- would a public Google calendar already address this issue?

We will look into improving the website later this year, so this is something we should consider.

**Comment by bencomp** [comment]
Apologies for not responding! I would like to contribute this feature, rather than use Google Calendar.
Perhaps it's better to make the calendar part a separate issue, as I think it requires changes to the template for events.
